name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "hello world!"
      - name: Print multi line shell commands 
        run: |
          echo "First output"
          echo "Second output"
      - name: Print goodbye
        run: echo "done - bye!"
